version: "3.8"
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      - TWOMES_DSN=root:twomes@tcp(db:3306)/twomes
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=twomes
      - MYSQL_ROOT_PASSWORD=twomes
