version: "3.8"
services:
  web:
    container_name: twomes-backoffice-api-local-web
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      - TWOMES_DSN=root:twomes@tcp(db:3306)/twomes
      - TWOMES_BASE_URL=http://localhost:8080
    depends_on:
      - db

  db:
    container_name: twomes-backoffice-api-local-db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=twomes
      - MYSQL_ROOT_PASSWORD=twomes
