name: CI Build

on:
  pull_request:

jobs:
  # Build executable for CI purposes
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup go
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      # Build executable
      - name: Build executable
        run: CGO_ENABLED=0 go build ./cmd/server/