name: Docker publish

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:

  # Build the docker container and publish it to GHCR
  docker:
    name: Build Docker image and push to GHCR
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup QEMU to support multiple platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Setup Docker buildx
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Auto generate image tags
      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/energietransitie/twomes-backoffice-api
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # Login to ghcr
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # # Release
      # - name: Release
      #   if: github.event_name != 'pull_request'
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true